# Data
path: 
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path')

kpt_shape: [8, 3] # [number of keypoints, number of dim]
flip_idx: [3, 2, 1, 0, 7, 6, 5, 4]

# Classes
# names:
#   0: Chair
#   1: Desk
#   2: Laptop
#   3: Monitor        
#   4: Window
#   5: Door
#   6: Sofa
#   7: Cabinet
#   8: Edge

names:
  0: Vertex
  1: Cabinet
  2: Common Chair
  3: Desk
  4: Door
  5: Laptop
  6: Monitor
  7: Office Chair
  8: Pendant
  9: Robotic Arm
  10: Sofa
  11: Window
